-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create users table (extends Supabase auth.users if needed, but here we keep it separate or linked)
-- Note: In Supabase, auth is handled by Gotrue. We usually create a public.users table that references auth.users.
-- For this migration, to keep it simple and compatible with existing logic, we'll create a public.users table.
-- Ideally, we should use a trigger to automatically create a public user when an auth user is created.

create table if not exists public.users (
  id uuid references auth.users on delete cascade not null primary key, -- Link to Supabase Auth User ID
  email text unique not null,
  name text not null,
  -- password_hash is NOT needed as Supabase handles auth
  subscription text default 'free' check (subscription in ('free', 'pro', 'team')),
  credits int default 100,
  credit_limit int default 100,
  code_runs int default 0,
  ai_queries int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_active timestamp with time zone default timezone('utc'::text, now()) not null,
  is_active boolean default true,
  username text unique,
  bio text,
  location text,
  website text,
  github text,
  twitter text,
  linkedin text,
  avatar_url text,
  profile_complete boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;

-- Create policies for users
create policy "Users can view their own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.users
  for update using (auth.uid() = id);

-- Create projects table
create table if not exists public.projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  name text not null,
  description text,
  file_tree jsonb, -- Postgres uses JSONB
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;

create policy "Users can view their own projects" on public.projects
  for select using (auth.uid() = user_id);

create policy "Users can insert their own projects" on public.projects
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own projects" on public.projects
  for update using (auth.uid() = user_id);

create policy "Users can delete their own projects" on public.projects
  for delete using (auth.uid() = user_id);

-- Create files table
create table if not exists public.files (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references public.projects(id) on delete cascade not null,
  filename text not null,
  original_name text not null,
  file_path text not null,
  file_size int default 0,
  mime_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.files enable row level security;

create policy "Users can view files of their projects" on public.files
  for select using (
    exists (
      select 1 from public.projects
      where projects.id = files.project_id
      and projects.user_id = auth.uid()
    )
  );

-- Create installed_packages table
create table if not exists public.installed_packages (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references public.projects(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  package_name text not null,
  package_spec text,
  installed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (project_id, package_name)
);

alter table public.installed_packages enable row level security;

-- Create daily_stats table
create table if not exists public.daily_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  date date not null,
  code_runs int default 0,
  ai_queries int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, date)
);

alter table public.daily_stats enable row level security;

-- Function to handle new user creation via Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
